# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-22 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180422_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='joinDate',
        ),
        migrations.AlterField(
            model_name='profile',
            name='contactInfo',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
