# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180422_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='', max_length=30),
        ),
    ]
