# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_wallpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallpost',
            old_name='creationdate',
            new_name='creationDate',
        ),
    ]
