# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180426_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='profilepic',
            field=models.FileField(default='C:\\Users\\Asus\\Desktop\\boi22\\boi2\\media\\default.png', null=True, upload_to='Profile_Picture'),
        ),
    ]
