# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.FileField(default='C:\\Users\\Asus\\Desktop\\boi22\\boi2\\media\\default.jpg', null=True, upload_to='Profile_Picture'),
        ),
    ]
