# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180429_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
