# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_servermessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servermessage',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='ServerMessage',
        ),
    ]
